"""empty message

Revision ID: 2f6dd79ccb4e
Revises: b36f901477fd
Create Date: 2025-07-07 19:03:14.526206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6dd79ccb4e'
down_revision = 'b36f901477fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['like'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('like')

    # ### end Alembic commands ###
